#'@title LGR Node Network
#'
#'@description Create data.frame describing all the observation nodes in the
#'  Lower Granite dam version of DABOM, including how they are related to one
#'  another. Modified on 1-15-19 to include additonal sites and branches for
#'  DABOM spawn year 2019
#'
#'@author Kevin See
#'
#'@import dplyr stringr
#'@export
#'@return NULL
#' @examples writeLGRNodeNetwork()

writeLGRNodeNetwork = function() {
  bin_names = c('Below_GRA',
                'Clearwater',
                'Grande_Ronde',
                'Imnaha',
                'Salmon',
                'Snake')

  bin_list = vector('list', length(bin_names))
  names(bin_list) = bin_names

  bin_list[['Below_GRA']] = list(
    'Tucannon' =
      list('LTR' =
             list(
               'LTR',
               'TUCR',
               'MTR' =
                 list('MTR',
                      'PATAHC',
                      'UTR' =
                        list('UTR',
                             'TUCH',
                             'TFH',
                             'CURP'))
             )),
    'Penawawa' = list('PENAWC'),
    'Almota' = list('ALMOTC'),
    'Below_GRA_Other' = list('158',
                             'SUN',
                             'SAT',
                             '15D',
                             '15MILC',
                             '15R',
                             '1890SC',
                             '18N',
                             '21MILC',
                             '30M',
                             '30MILC',
                             '30ML2C',
                             '3D1',
                             '3D2',
                             '3D3',
                             '3D4',
                             '3MILC',
                             '3MILIS',
                             '85M',
                             '9MILEC',
                             'AB1',
                             'AB2',
                             'AB3',
                             'AB4',
                             'ABEH',
                             'ABERC',
                             'AEN',
                             'AENEAC',
                             'AHSH',
                             'AHTANC',
                             'AHTANF',
                             'AMERIR',
                             'ANT',
                             'ANTELC',
                             'ANTOIC',
                             'APROOK',
                             'B1J',
                             'B2A',
                             'B2J',
                             'BAD',
                             'BADGEI',
                             'BAKEOC',
                             'BANKSL',
                             'BARNAC',
                             'BBC',
                             'BBP',
                             'BBT',
                             'BCC',
                             'BCHINL',
                             'BCKROC',
                             'BCL',
                             'BCLFBY',
                             'BCLTAL',
                             'BCP',
                             'BCTRAP',
                             'BDP',
                             'BEAR2C',
                             'BEAR3C',
                             'BEAR5C',
                             'BEAV2C',
                             'BEAV3C',
                             'BEAV3P',
                             'BEECEF',
                             'BEECHC',
                             'BERRYC',
                             'BGM',
                             'BGMTAL',
                             'BHL',
                             'BIDDLP',
                             'BIG1C',
                             'BIG3C',
                             'BIGC',
                             'BIGMEC',
                             'BIGWSP',
                             'BIRCHC',
                             'BIRCHE',
                             'BIRCHW',
                             'BLDRCK',
                             'BLDRNF',
                             'BLDRSF',
                             'BLKBAS',
                             'BLNDSL',
                             'BLUEC',
                             'BMT',
                             'BO1',
                             'BO1BYP',
                             'BO1GWL',
                             'BO2',
                             'BO2BCC',
                             'BO2BYP',
                             'BO2GAT',
                             'BO2GWL',
                             'BO2ORI',
                             'BO2RRR',
                             'BO3',
                             'BO4',
                             'BON',
                             'BONAFF',
                             'BONAPC',
                             'BONH',
                             'BONLD1',
                             'BONLD2',
                             'BONLD3',
                             'BONMRT',
                             'BONP',
                             'BOSTCC',
                             'BPC',
                             'BR0',
                             'BR1',
                             'BR2',
                             'BR3',
                             'BRDG2C',
                             'BRDG3C',
                             'BREITR',
                             'BRENNC',
                             'BRIDGC',
                             'BRIDWB',
                             'BRUS2C',
                             'BSH',
                             'BSHPCK',
                             'BUCK3C',
                             'BUCKAP',
                             'BUCKC',
                             'BUCKHC',
                             'BUCKSL',
                             'BUMPR',
                             'BURL',
                             'BUTCHC',
                             'BUTCHP',
                             'BVC',
                             'BVJ',
                             'BVP',
                             'BVRLYI',
                             'BVT',
                             'BVX',
                             'BWL',
                             'CABLNF',
                             'CAL',
                             'CALAPR',
                             'CAMP2C',
                             'CAMPC',
                             'CANDLC',
                             'CANY3C',
                             'CANY4C',
                             'CAP',
                             'CARP',
                             'CARS',
                             'CASC',
                             'CASS',
                             'CBD',
                             'CBDFBY',
                             'CBL',
                             'CBLAIS',
                             'CBS',
                             'CCC',
                             'CCM',
                             'CCS',
                             'CCT',
                             'CDP',
                             'CEDARC',
                             'CFCT',
                             'CFD',
                             'CFDNSC',
                             'CFDSF2',
                             'CFDSF3',
                             'CFDTAL',
                             'CFF',
                             'CFJ',
                             'CGJ',
                             'CGR',
                             'CGRTAL',
                             'CHANDL',
                             'CHEL',
                             'CHELAR',
                             'CHEWEC',
                             'CHEWUP',
                             'CHEWUR',
                             'CHFARF',
                             'CHIKAC',
                             'CHINOR',
                             'CHIP',
                             'CHIW',
                             'CHIWAC',
                             'CHIWAR',
                             'CHIWAT',
                             'CHJO',
                             'CHL',
                             'CHM',
                             'CHP',
                             'CHU',
                             'CHUMSC',
                             'CHW',
                             'CIC',
                             'CISPUR',
                             'CJP',
                             'CLARFP',
                             'CLCKMS',
                             'CLE',
                             'CLEA2C',
                             'CLEA3C',
                             'CLEARP',
                             'CLEBYP',
                             'CLEE',
                             'CLEFBY',
                             'CLELMD',
                             'CLELMR',
                             'CLETAL',
                             'CLP',
                             'CLRBR',
                             'COLR1',
                             'COLR2',
                             'COLR3',
                             'COLR4',
                             'COLR5',
                             'COLR6',
                             'COLR7',
                             'COLR8',
                             'COLR9',
                             'COLVLE',
                             'COONSC',
                             'COP',
                             'COPPEC',
                             'COTN2C',
                             'COTTWC',
                             'COULTC',
                             'COULTP',
                             'COWEAP',
                             'COWEER',
                             'COWICC',
                             'COWISF',
                             'COWLR1',
                             'COWLR2',
                             'COWS',
                             'COWT',
                             'COYO2C',
                             'COYOTC',
                             'CR1',
                             'CR2',
                             'CR3',
                             'CRABP',
                             'CRESCB',
                             'CRESIS',
                             'CROOK1',
                             'CROWC',
                             'CRTRAP',
                             'CRU',
                             'CRW',
                             'CUBC',
                             'CUNNSL',
                             'CWP',
                             'DAVISC',
                             'DAYP',
                             'DBH',
                             'DBO',
                             'DEAD2C',
                             'DEAD3C',
                             'DEADNF',
                             'DEEPCK',
                             'DESCH1',
                             'DESCH2',
                             'DET',
                             'DETFBY',
                             'DETTAL',
                             'DEX',
                             'DEXTAL',
                             'DHORNC',
                             'DILACC',
                             'DOGRVR',
                             'DRANOL',
                             'DRIFTC',
                             'DRM',
                             'DRNP',
                             'DRP',
                             'DRY',
                             'DRY3C',
                             'DRYC',
                             'DRYFBY',
                             'DRYFCC',
                             'DRYP',
                             'DRYTAL',
                             'DSF',
                             'DUNCAN',
                             'DXP',
                             'EAG2NF',
                             'EAGH',
                             'EAGL2C',
                             'EARLWC',
                             'EASTOP',
                             'EBNK',
                             'EBO',
                             'ECH',
                             'ECL',
                             'EDEERC',
                             'EFD',
                             'EFHORC',
                             'EHL',
                             'EIGH2C',
                             'EIGHTC',
                             'ELRH',
                             'EMC',
                             'ENA',
                             'ENF',
                             'ENL',
                             'ENM',
                             'ENS',
                             'ENTH',
                             'ENTIAR',
                             'ENTRTP',
                             'ESANIS',
                             'ESJ',
                             'ESX',
                             'ETIENC',
                             'EWC',
                             'FAL',
                             'FALL2C',
                             'FALTAL',
                             'FDC',
                             'FDD',
                             'FDDFBY',
                             'FDDTAL',
                             'FEEDCN',
                             'FIRSTC',
                             'FIVE2C',
                             'FOGDEW',
                             'FOL',
                             'FOS',
                             'FOSFBY',
                             'FOSTAL',
                             'FOSTC',
                             'FOUNDI',
                             'FOXC',
                             'FST',
                             'GABLEC',
                             'GATEC',
                             'GEECR',
                             'GERMC',
                             'GL2',
                             'GLC',
                             'GOA',
                             'GOATWP',
                             'GOJ',
                             'GOLD2C',
                             'GOLD3C',
                             'GOLD4C',
                             'GOOS2I',
                             'GOOSEI',
                             'GRAYH',
                             'GRAYSR',
                             'GRBLDC',
                             'GREENR',
                             'GREEPC',
                             'GRJ',
                             'GRX',
                             'GWP',
                             'HADENC',
                             'HADESF',
                             'HALLC',
                             'HANGC',
                             'HANSPC',
                             'HANTWN',
                             'HANWTB',
                             'HATRCK',
                             'HCR',
                             'HCRFBY',
                             'HCRREG',
                             'HCRTUR',
                             'HERMAC',
                             'HINDOC',
                             'HLK',
                             'HLKTAL',
                             'HLX',
                             'HN1',
                             'HN2',
                             'HN3',
                             'HOODEF',
                             'HOODMF',
                             'HOODR',
                             'HOODWF',
                             'HORS2C',
                             'HRM',
                             'HS1',
                             'HS2',
                             'HSL',
                             'HSM',
                             'HST',
                             'HSU',
                             'I-90B',
                             'ICH',
                             'ICICLC',
                             'ICL',
                             'ICM',
                             'ICTRAP',
                             'ICU',
                             'IHA',
                             'IHR',
                             'IHRBYP',
                             'IHRCOL',
                             'IHRSPF',
                             'IHRSPL',
                             'IHRTAL',
                             'IHRTRB',
                             'IMQP',
                             'INDI2C',
                             'INDINC',
                             'INKANC',
                             'IRON2C',
                             'IRRI',
                             'IS18',
                             'JACK2C',
                             'JACKC',
                             'JACKCP',
                             'JCJ',
                             'JD1',
                             'JDA',
                             'JDABYP',
                             'JDACOL',
                             'JDAFBY',
                             'JDAGAT',
                             'JDAGWL',
                             'JDALD1',
                             'JDALD2',
                             'JDAMRT',
                             'JDAR1',
                             'JDAR2',
                             'JDARMF',
                             'JDARNF',
                             'JDARRR',
                             'JDARSF',
                             'JDATAL',
                             'JDJ',
                             'JDM',
                             'JNSCAS',
                             'JO1',
                             'JO2',
                             'JOH',
                             'JOHN2C',
                             'JPT',
                             'JSFBC',
                             'JSFDC',
                             'JSFMC',
                             'JSFWC',
                             'JUNGLC',
                             'KALA',
                             'KALAMR',
                             'KCB',
                             'KETTLR',
                             'KLICKR',
                             'KLIH',
                             'KLR',
                             'LAKE2C',
                             'LAKE3C',
                             'LAKEBR',
                             'LASTC',
                             'LAURLK',
                             'LBC',
                             'LBLDRC',
                             'LBRIC',
                             'LBT',
                             'LD1',
                             'LD2',
                             'LD3',
                             'LD4',
                             'LEA',
                             'LEAB',
                             'LEABYP',
                             'LEAFBY',
                             'LEATAL',
                             'LEAV',
                             'LEB',
                             'LEBFBY',
                             'LEBLDS',
                             'LEL',
                             'LEMONC',
                             'LENLKE',
                             'LEWCLK',
                             'LEWH',
                             'LEWIEF',
                             'LEWISP',
                             'LEWISR',
                             'LFF',
                             'LGR',
                             'LGRBPS',
                             'LGRBYP',
                             'LGRCOL',
                             'LGRDTG',
                             'LGRDWT',
                             'LGRFBY',
                             'LGRGAT',
                             'LGRGWL',
                             'LGRICE',
                             'LGRMRT',
                             'LGROFL',
                             'LGRORI',
                             'LGRRBR',
                             'LGRRRR',
                             'LGRRTR',
                             'LGRRXR',
                             'LGRSEP',
                             'LGRSPL',
                             'LGRSTS',
                             'LGRTAL',
                             'LGRTRB',
                             'LGS',
                             'LGSBPS',
                             'LGSBYP',
                             'LGSCOL',
                             'LGSDTG',
                             'LGSDWT',
                             'LGSFBY',
                             'LGSGAT',
                             'LGSGWL',
                             'LGSICE',
                             'LGSMRT',
                             'LGSOFL',
                             'LGSORI',
                             'LGSRBR',
                             'LGSRRR',
                             'LGSRTR',
                             'LGSRXR',
                             'LGSSEP',
                             'LGSSPL',
                             'LGSSTS',
                             'LGSTAL',
                             'LGSTRB',
                             'LHC',
                             'LIBBYC',
                             'LICK3C',
                             'LINEC',
                             'LITTLC',
                             'LKLICR',
                             'LKR',
                             'LLC',
                             'LMA',
                             'LMC',
                             'LMEMIS',
                             'LMILIS',
                             'LMJ',
                             'LMN',
                             'LMNBPS',
                             'LMNBYP',
                             'LMNCOL',
                             'LMNDTG',
                             'LMNDWT',
                             'LMNFBY',
                             'LMNGAT',
                             'LMNGWL',
                             'LMNICE',
                             'LMNMRT',
                             'LMNOFL',
                             'LMNORI',
                             'LMNRBR',
                             'LMNRRR',
                             'LMNRTR',
                             'LMNRXR',
                             'LMNSEP',
                             'LMNSPL',
                             'LMNSTS',
                             'LMNTAL',
                             'LMNTRB',
                             'LMONIS',
                             'LMR',
                             'LMT',
                             'LNF',
                             'LNR',
                             'LNSANR',
                             'LOGCC',
                             'LOGYC',
                             'LONERC',
                             'LOONYC',
                             'LOP',
                             'LOPTAL',
                             'LOR',
                             'LOSTC',
                             'LOSTR',
                             'LOUIEC',
                             'LOUPLC',
                             'LRSNKC',
                             'LTNACR',
                             'LTNANF',
                             'LTP',
                             'LUNION',
                             'LWBEAR',
                             'LWCEDR',
                             'LWD',
                             'LWDTAL',
                             'LWE',
                             'LWENAT',
                             'LWISSQ',
                             'LWL',
                             'LWN',
                             'LWSALR',
                             'LWSCCL',
                             'LWSCFC',
                             'LWSCMC',
                             'LWSCML',
                             'LWSH',
                             'LYFE',
                             'LYLFAT',
                             'M3R',
                             'MAD',
                             'MADRVR',
                             'MANASC',
                             'MANCRS',
                             'MARI',
                             'MARIOC',
                             'MARION',
                             'MASON',
                             'MC1',
                             'MC2',
                             'MCD',
                             'MCI',
                             'MCITAL',
                             'MCJ',
                             'MCKA2C',
                             'MCKAYC',
                             'MCKE',
                             'MCKER',
                             'MCKESF',
                             'MCL',
                             'MCN',
                             'MCNBPS',
                             'MCNBYP',
                             'MCNCOL',
                             'MCNDTG',
                             'MCNDWT',
                             'MCNFBY',
                             'MCNGAT',
                             'MCNGWL',
                             'MCNICE',
                             'MCNLD1',
                             'MCNMRT',
                             'MCNOFL',
                             'MCNORI',
                             'MCNRBR',
                             'MCNRRR',
                             'MCNRTR',
                             'MCNRXR',
                             'MCNSEP',
                             'MCNSPL',
                             'MCNSRR',
                             'MCNSTS',
                             'MCNTAL',
                             'MCNTRB',
                             'MCX',
                             'MDR',
                             'MDSH',
                             'MDVAP',
                             'MEACHC',
                             'MEACHE',
                             'MEACHN',
                             'MEG',
                             'MEGC',
                             'MERH',
                             'METH',
                             'METHR',
                             'METOLR',
                             'METRO',
                             'METTRP',
                             'MFD',
                             'MFDFTF',
                             'MFDLBN',
                             'MFDLBS',
                             'MFDSEP',
                             'MFLBC',
                             'MHB',
                             'MHP',
                             'MHPFBY',
                             'MHPTAL',
                             'MILL3C',
                             'MILL4C',
                             'MILLC',
                             'MINP',
                             'MIS2EF',
                             'MISS2C',
                             'MISSNC',
                             'MJ1',
                             'MLAK2C',
                             'MLRSNI',
                             'MOLALR',
                             'MONT',
                             'MOONSC',
                             'MOSESC',
                             'MRB',
                             'MRC',
                             'MRT',
                             'MRW',
                             'MSANTR',
                             'MSB',
                             'MSC',
                             'MSH',
                             'MSKF',
                             'MSLA2C',
                             'MTD',
                             'MUDDYP',
                             'MUDDYR',
                             'MULTCH',
                             'MURDSF',
                             'MVF',
                             'MVFLAP',
                             'MVP',
                             'MWC',
                             'MWE',
                             'MWF',
                             'MXWLCN',
                             'NAF',
                             'NAL',
                             'NAPEEC',
                             'NAS',
                             'NASONC',
                             'NATCHR',
                             'NAU',
                             'NBA',
                             'NBG',
                             'NBGFBY',
                             'NBGTAL',
                             'NEALC',
                             'NES',
                             'NESPR',
                             'NFCHEW',
                             'NFLBC',
                             'NFT',
                             'NFTEAN',
                             'NFW',
                             'NILEC',
                             'NMC',
                             'NNANAC',
                             'NSANTR',
                             'NSB',
                             'NSCAPC',
                             'NSM',
                             'NSS',
                             'OAKC',
                             'OASP',
                             'OBF',
                             'OCHOCC',
                             'OKANR',
                             'OKC',
                             'OKI',
                             'OKL',
                             'OKP',
                             'OKRCRY',
                             'OKS',
                             'OKV',
                             'OKW',
                             'OMAKC',
                             'OMAKP',
                             'OMF',
                             'OMK',
                             'OMP',
                             'ONAF',
                             'ONC',
                             'ONIONC',
                             'ORB',
                             'OSOYBR',
                             'OSOYHA',
                             'OSOYOL',
                             'OXBH',
                             'PANT2C',
                             'PARK',
                             'PAT',
                             'PATITC',
                             'PD1',
                             'PD2',
                             'PD7',
                             'PEARSC',
                             'PEL',
                             'PELTON',
                             'PENP',
                             'PER',
                             'PERAFT',
                             'PERTAL',
                             'PES',
                             'PESHAR',
                             'PEU',
                             'PINEC',
                             'PINHC',
                             'POTATC',
                             'POTHOL',
                             'PRA',
                             'PRD',
                             'PRDFBY',
                             'PRDGWL',
                             'PRDH',
                             'PRDLD1',
                             'PRDMRT',
                             'PRDTAL',
                             'PRH',
                             'PRJ',
                             'PRO',
                             'PROFBY',
                             'PROH',
                             'PROSRD',
                             'PROSRR',
                             'PROTAL',
                             'PROTRP',
                             'PRV',
                             'PWD',
                             'PWDFBY',
                             'QRTZC',
                             'RAMSYC',
                             'RATTLC',
                             'RBF',
                             'RCJ',
                             'RCK5RF',
                             'RCL',
                             'RCS',
                             'RCT',
                             'RCX',
                             'REECEC',
                             'RFP',
                             'RGRSPC',
                             'RI2BYP',
                             'RIA',
                             'RICEIS',
                             'RICHIS',
                             'RINH',
                             'RIS',
                             'RISFWC',
                             'RISMRT',
                             'RISTAL',
                             'RIVERP',
                             'ROARC',
                             'ROBU',
                             'ROCK2C',
                             'ROCK3C',
                             'ROCK4C',
                             'ROCK5C',
                             'ROCKC',
                             'ROCKIS',
                             'ROLFIP',
                             'ROSAD',
                             'ROU',
                             'ROUFTF',
                             'ROUTAL',
                             'ROZ',
                             'ROZBYP',
                             'ROZFBY',
                             'ROZLDR',
                             'ROZTAL',
                             'RRE',
                             'RREBYP',
                             'RRERRR',
                             'RRETAL',
                             'RRF',
                             'RRJ',
                             'RSB',
                             'RSH',
                             'RSNAKC',
                             'RSNANF',
                             'RSSNIS',
                             'RVP',
                             'RYANC',
                             'RZF',
                             'SA0',
                             'SA1',
                             'SALMOC',
                             'SANPR',
                             'SANPWF',
                             'SANTIR',
                             'SATUSC',
                             'SCAPPB',
                             'SCAPPC',
                             'SCHAFC',
                             'SCL',
                             'SCP',
                             'SERH',
                             'SFCHEW',
                             'SFL',
                             'SFLBC',
                             'SGOLDC',
                             'SGP',
                             'SHATFD',
                             'SHERFT',
                             'SHIMC',
                             'SHINGC',
                             'SHK',
                             'SHP',
                             'SHPFBY',
                             'SHPTAL',
                             'SHTIKC',
                             'SHUTTC',
                             'SILVEC',
                             'SIMCNF',
                             'SIMCOC',
                             'SIMILP',
                             'SIMILR',
                             'SIMP',
                             'SIP',
                             'SJ1',
                             'SJ2',
                             'SKA',
                             'SKAHAL',
                             'SKAM',
                             'SKATAL',
                             'SKIPAR',
                             'SKIPAW',
                             'SKOKNF',
                             'SNAKE1',
                             'SNAKE2',
                             'SNANAC',
                             'SND',
                             'SNDTAP',
                             'SNYDEC',
                             'SPOKR1',
                             'SPOKR2',
                             'SPRC',
                             'SQAW3C',
                             'SQAW4C',
                             'SQAWC',
                             'SR1',
                             'SR2',
                             'SSANTR',
                             'SSC',
                             'SSD',
                             'SSDSRR',
                             'SSDTAL',
                             'SSIDEC',
                             'SSIDES',
                             'SSJ',
                             'STAFFC',
                             'STAPAC',
                             'STFH',
                             'STMARP',
                             'STOR2C',
                             'SUC',
                             'SUJ',
                             'SUL',
                             'SULBPS',
                             'SULBYP',
                             'SULFBY',
                             'SULFDS',
                             'SULSEP',
                             'SULTRB',
                             'SUMI2C',
                             'SUMI3C',
                             'SWALEC',
                             'SWAUKC',
                             'SWC',
                             'SWK',
                             'TAN',
                             'TANESF',
                             'TANEUC',
                             'TANNEC',
                             'TC4',
                             'TCM',
                             'TCT',
                             'TD1',
                             'TD2',
                             'TDA',
                             'TDAICE',
                             'TDAMRT',
                             'TDASPF',
                             'TDASPL',
                             'TDASPT',
                             'TDATAL',
                             'TDATRB',
                             'TEANAR',
                             'TEANMF',
                             'TEANWF',
                             'TENNAI',
                             'TEPEEC',
                             'TEPEEF',
                             'TEXC',
                             'THOMC',
                             'THOP',
                             'TIETNR',
                             'TILLIC',
                             'TLT',
                             'TMA',
                             'TMF',
                             'TMFFBY',
                             'TMFTAL',
                             'TMJ',
                             'TNK',
                             'TON',
                             'TONASC',
                             'TOP',
                             'TOPPEC',
                             'TOUCHR',
                             'TOULOU',
                             'TOUT',
                             'TOUTLR',
                             'TOUTNF',
                             'TR1',
                             'TR2',
                             'TRC',
                             'TRINR',
                             'TRONC',
                             'TROU2C',
                             'TROUTC',
                             'TRYOC',
                             'TSHIMC',
                             'TSUGCR',
                             'TUF',
                             'TUM',
                             'TUMFBY',
                             'TUNKC',
                             'TURNCR',
                             'TURO',
                             'TUTUIC',
                             'TWIS2P',
                             'TWISPP',
                             'TWISPR',
                             'TWISPW',
                             'TWITRP',
                             'TWR',
                             'TWX',
                             'TY1',
                             'TY2',
                             'TY3',
                             'TY4',
                             'UCT',
                             'UKNWRC',
                             'UM1',
                             'UM2',
                             'UMAH',
                             'UMAR',
                             'UMATNF',
                             'UMATSF',
                             'UMC',
                             'UMF',
                             'UMPQAR',
                             'UMR',
                             'UMT',
                             'UMTANC',
                             'UMW',
                             'UNT',
                             'UPT',
                             'URT',
                             'UWE',
                             'UWH',
                             'VASEUX',
                             'VDS3',
                             'VGISNB',
                             'VIENTC',
                             'VNGRC',
                             'WAHA',
                             'WAJ',
                             'WALLAR',
                             'WALLIS',
                             'WALLNF',
                             'WALLSF',
                             'WAN',
                             'WANACC',
                             'WANBYP',
                             'WANFBY',
                             'WANGWL',
                             'WANLD1',
                             'WANLD2',
                             'WANMRT',
                             'WANSPL',
                             'WANTAL',
                             'WANTRB',
                             'WAP',
                             'WAPATC',
                             'WAPATD',
                             'WAPATS',
                             'WAPSRR',
                             'WAPTAL',
                             'WARMSR',
                             'WASHOR',
                             'WASHWF',
                             'WE1',
                             'WE2',
                             'WEA',
                             'WEH',
                             'WEJ',
                             'WEL',
                             'WELFBY',
                             'WELH',
                             'WELLD1',
                             'WELLD2',
                             'WELSBR',
                             'WELTAL',
                             'WENA2T',
                             'WENA3T',
                             'WENA4T',
                             'WENASC',
                             'WENATL',
                             'WENATR',
                             'WENATT',
                             'WFC',
                             'WFF',
                             'WHC',
                             'WHEELC',
                             'WHITEC',
                             'WHITER',
                             'WHITPC',
                             'WHITSR',
                             'WHITWF',
                             'WHS',
                             'WHSH',
                             'WIDOWC',
                             'WILD2C',
                             'WILDSC',
                             'WILH',
                             'WILL',
                             'WILL2C',
                             'WILLR1',
                             'WILLR2',
                             'WILLR3',
                             'WILMOC',
                             'WILPB',
                             'WILRMF',
                             'WILSN2',
                             'WILSNC',
                             'WIND2R',
                             'WINT',
                             'WINTBC',
                             'WL1',
                             'WL2',
                             'WLT',
                             'WOLFC',
                             'WOODIS',
                             'WOPTXD',
                             'WPJ',
                             'WPT',
                             'WPX',
                             'WPXTAL',
                             'WRNFMF',
                             'WRP',
                             'WRU',
                             'WSH',
                             'WSPH',
                             'WSR',
                             'WTL',
                             'WW1',
                             'WW2',
                             'WYCHUC',
                             'WZDF',
                             'Y1J',
                             'YAKIM1',
                             'YAKIM2',
                             'YELHKC',
                             'YHC',
                             'YOUNGB',
                             'ZSL')
  )

  bin_list[['Clearwater']] = list(
    'Lapwai' = list('LAP' =
                      list(
                        'LAP',
                        'LAPC',
                        'MIS' =
                          list('MIS',
                               'MISSC'),
                        'SWT' =
                          list('SWT',
                               'SWEETC',
                               'WEB' =
                                 list('WEB',
                                      'WEBBC'))
                      )),
    'Potlatch' = list(
      'JUL' =
        list(
          'JUL',
          'BOBSC',
          'BOUL3C',
          'CEDA2C',
          'CORRAC',
          'LBOULC',
          'LEOPOC',
          'MPOTLC',
          'PIVASC',
          'POTR',
          'POTREF',
          'KHS' =
            list('KHS',
                 'LBEARC',
                 'LBCWF',
                 'BBA' =
                   list('BBA',
                        'BIGBEC')),
          'HLM' =
            list('HLM',
                 'COUG2C',
                 'FEATHC',
                 'MOOS3C',
                 'POTRWF',
                 'PURDUC'),
          'PCM' =
            list('PCM',
                 'PINE2C')
        )),
    'Lolo' = list('LC1' =
                    list('LC1',
                         'LC2' =
                           list(
                             'LC2',
                             'ELDORC',
                             'LOLOC'
                           ))),
    'SFClearwater' = list('SC1' =
                            list(
                              'SC1',
                              'SC2' =
                                list(
                                  'SC2',
                                  'AMERR',
                                  'CROOKP',
                                  'CROOKR',
                                  'CROP',
                                  'CROTRP',
                                  'CROW',
                                  'CRT',
                                  'FIVEMC',
                                  'JOHNC',
                                  'LUGUAF',
                                  'MEAD2C',
                                  'MILL2C',
                                  'NEWSOC',
                                  'REDP',
                                  'REDR',
                                  'REDRSF',
                                  'REDTRP',
                                  'RELIEC',
                                  'RRT',
                                  'TENMIC',
                                  'TWNMIC',
                                  'TWNMIT'
                                )
                            )),
    'ClearCreek' = list('CLC' =
                          list('CLC',
                               'KOOS',
                               'CLEARC')),
    'Selway' = list(
      'SW1' =
        list(
          'SW1',
          'CEFLAF',
          'OHARAC',
          'SW2' =
            list(
              'SW2',
              '3LINKC',
              'BEARC',
              'EAGLEC',
              'GEDCWF',
              'GEDNEC',
              'MEADOC',
              'MINKC',
              'MOOS2C',
              'MOOS2N',
              'RUNNIC',
              'SELWY2',
              'WHITCC'
            )
        )),
    'Lochsa' = list('LRL' =
                      list(
                        'LRL',
                        'LRU' =
                          list(
                            'LRU',
                            'BIGFLC',
                            'BOULDC',
                            'BOUTRP',
                            'BRUSHC',
                            'CANYOC',
                            'CFCTRP',
                            'COLTC',
                            'COLTKC',
                            'CROOKC',
                            'DEADMC',
                            'LOCHSA',
                            'OLDMAC',
                            'PAPOOC',
                            'PETEKC',
                            'POSTOC',
                            'POWP',
                            'SQUAWC',
                            'STORMC',
                            'WARMSC',
                            'WHITSC',
                            'FISTRP' =
                              list('FISTRP',
                                   'FISHC',
                                   'HUNGC')
                          )
                      )),
    'Clearwater_Other' = list(
      'BCCAP',
      'BEDRKC',
      'BIGCAC',
      'CLJ',
      'CLWH',
      'CLWHNF',
      'CLWR',
      'CLWRMF',
      'CLWRNF',
      'CLWRSF',
      'CLWTRP',
      'COTNWC',
      'DWL',
      'DWOR',
      'DWORMS',
      'DWORNF',
      'JACKSC',
      'LITCAC',
      'LOCTRP',
      'SELWY1',
      'NPTH',
      'OROFC',
      'SWSP'
    )
  )

  bin_list[['Snake']] = list(
    'Asotin' = list('ACM' =
                      list(
                        'ACM',
                        'GEORGC',
                        'ASOTIC' =
                          list('ASOTIC',
                               'ACB' =
                                 list(
                                   'ACB',
                                   'AFC' =
                                     list('AFC',
                                          'ASOTNF',
                                          'ASOTSF'),
                                   'CCA' =
                                     list('CCA',
                                          'CHARLC')
                                 ))
                      )),
    'Alpowa' = list('ALPOWC'),
    'TenMileCreek' = list('TENMC2'),
    'Snake_Other' = list(
      'CATHEC',
      'CJRAP',
      'COTP',
      'COUGRC',
      'CTWD3C',
      'GRAND1',
      'GRAND2',
      'GRNTRP',
      'HCD',
      'HCDTAL',
      'IMJ',
      'IMNAHR',
      'IMNTRP',
      'OXBO',
      'PLAP',
      'SNAKE3',
      'SNAKE4',
      'SNJ',
      'SNKTRP',
      'WALLOR'
    )
  )

  bin_list[['Grande_Ronde']] = list(
    'Joseph_Creek' = list('JOC' =
                            list('JOC',
                                 'JOSEPC')),
    'Wenaha' =
      list('WEN' =
             list('WEN',
                  'WENR',
                  'WENRNF',
                  'WENRSF')),
    'LookingGlass' =
      list('LOOKGC',
           'LOOH'),
    'Upper_Grande_Ronde' =
      list('UGR' =
             list('UGR',
                  'UGS' =
                    list('UGS',
                         'GRANDW'),
                  'CCW' =
                   list('CCW',
                        'CATHEW',
                        'CATCMF',
                        'CATCNF',
                        'CATCSF',
                        'CATHEP',
                        'CCP',
                        'LCATHC')
      )),
    'Wallowa' =
      list(
        'WR1' =
          list('WR1',
               'BCANF',
               'WR2' =
                 list('WR2',
                      'WALH',
                      'LOSTIW' =
                        list('LOSTIW',
                             'LOSTIR')),
               'MR1' =
                 list('MR1',
                      'MINAMR')))
  )

  bin_list[['Imnaha']] = list('Cow_Creek' =
                                list('COC' =
                                       list('COC',
                                            'COWCR')),
                              'ImnahaRiver' =
                                list('IR1' =
                                       list('IR1',
                                            'LITNGC',
                                            'IR2' =
                                              list('IR2',
                                                   'CMP' =
                                                     list('CMP',
                                                          'CAMP4C'),
                                                   'BSC' =
                                                     list('BSC',
                                                          'BSHEEC',
                                                          'LICK2C',
                                                          'SALTC'),
                                                   'LSHEEF' =
                                                     list('LSHEEF',
                                                          'LSHEEC',
                                                          'MCCULC',
                                                          'CANALC',
                                                          'REDMOC'),
                                                   'HORS3C',
                                                   'IR3' =
                                                     list('IR3',
                                                          'CZY' =
                                                            list('CZY',
                                                                 'CRAZYC'),
                                                          'FREEZC',
                                                          'MAHOGC',
                                                          'IR4' =
                                                            list('IR4',
                                                                 'IML' =
                                                                   list('IML',
                                                                        'IMNAHW' =
                                                                          list('IMNAHW',
                                                                               'IR5' =
                                                                                 list('IR5',
                                                                                      'GUMBTC',
                                                                                      'DRY2C'))
                                                                   ))
                                                     )
                                              )
                                       )))

  bin_list[['Salmon']] = list(
    'Rapid_River' =
      list('RAPH',
           'RPDTRP',
           'RAPIWF',
           'RPJ'),
    'SF_Salmon' =
      list(
        'SFG' =
          list('SFG',
               'ELK2C',
               'FITSUC',
               'LSFTRP',
               'SAEFSF',
               'SFSRKT',
               'ZEN' =
                 list('ZEN',
                      'ALEXC',
                      'FLATC',
                      'GROUSC',
                      'LAKEC',
                      'LICKC',
                      'PIAHC',
                      'RUBYC',
                      'SECTRP',
                      'SECESR',
                      'SUMITC',
                      'ZENAC',
                      'ZENAWF'
                 ),
               'KRS' =
                 list('KRS',
                      'BCKHRC',
                      'CAMP3C',
                      'GOATC',
                      'PHOEBC',
                      'SALRSF',
                      'STR' =
                        list('STR',
                             'SFSTRP',
                             'KNOXB',
                             'MCCA',
                             'SALSFW'=
                               list('SALSFW',
                                    'BEAR4C',
                                    'RICEC',
                                    'STOLP')
                        )
                 ),
               'ESS' =
                 list('ESS',
                      'SUGARC',
                      'YPP' =
                        list('YPP',
                             'YPPL'),
                      'JOHTRP',
                      'JOHNSC' =
                        list('JOHNSC',
                             'BURNLC')
                 )
          )),
    'Big_Creek' =
      list('TAY' =
             list('TAY',
                  'BEAV4C',
                  'BIG2C',
                  'BIG2CT',
                  'BRAMYC',
                  'BUCK2C',
                  'CABINC',
                  'CAVEC',
                  'CROO2C',
                  'LOGANC',
                  'MONCWF',
                  'MONUMC',
                  'RUSHC',
                  'RUSHWF',
                  'SMITHC',
                  'SNOSLC'
             )
      ),
    'MFSR_Other' =
      list('BEAVC',
           'BOUNDC',
           'CAMASC',
           'CAPEHC',
           'DAGGEC',
           'ELKC',
           'FALLC',
           'INDIAC',
           'KNAPPC',
           'LOONC',
           'MARSHC',
           'MARTRP',
           'MARTR2',
           'PISTOC',
           'RAPR',
           'SALMF1',
           'SALMF2',
           'SALRMF',
           'SHEPC',
           'SULFUC',
           'WILSOC',
           'YELLJC'),
    'Bear_Valley' =
      list('BRC' =
             list('BRC',
                  'BEARVC')
      ),
    'Carmen_Creek' =
      list('CRC' =
             list('CRC',
                  'CARMEC')
      ),
    'Panther_Creek' =
      list('PCA' =
             list('PCA',
                  'MOYERC',
                  'MUSCRC',
                  'PANTHC')
      ),
    'NFSalmon' =
      list('NFS' =
           list('NFS',
           'SALRNF')),

  'Lemhi' =
    list(
      'LLR' =
        list(
          'LLR',
          'HAYNSC',
          'LEMHIR',
          'LLRTP',
          'MCDEVC',
          'PATTEC',
          'PRATTC',
          'S2I',
          'S2O',
          'WITHGC',
          'BHC' =
            list('BHC',
                 'BOHANC',
                 'BOHEFC'),
          'WPC' =
            list('WPC',
                 'WIMPYC'),
          'KEN' =
            list('KEN',
                 'KENYC'),
          'AGC' =
            list('AGC',
                 'AGNCYC',
                 'COW2C',
                 'FLUMEC'),
          'HYC' =
            list(
              'HYC',
              'BASINC',
              'BUCK4C',
              'BVAL2C',
              'HAYDEF',
              'HAYDNC',
              'HYDTRP',
              'TRAILC',
              'WRIGTC'
            ),
          'LRW' =
            list(
              'LRW',
              'BIGB2C',
              'DEERC',
              'LEMHIW',
              'LEMTRP',
              'LIT8MC',
              'MILL5C',
              'QKASPC',
              'RESVRC',
              'YRIANC',
              'LLS' =
                list('LLS',
                     'LLSPRC'),
              'LB8' =
                list('LB8',
                     'BIG8MC'),
              'LBS' =
                list('LBS',
                     'BIGSPC'),
              'LCL' =
                list('LCL',
                     'LEEC'),
              'BTC' =
                list('BTC',
                     'BTL' =
                       list(
                         'BTL',
                         'BTIMBC',
                         'BTM' =
                           list('BTM',
                                'LTIMBC',
                                'BTU' =
                                  list('BTU',
                                       'BASN2C'))
                       )),
              'CAC' =
                list('CAC',
                     'CANY2C',
                     'CRUIKS',
                     'WILDCC'),
              'HEC' =
                list('HEC',
                     'HAWLYC'),
              '18M' =
                list('18M',
                     '18MILC',
                     'TEXASC')
            ))),

  'Upper_Salmon' = list(
    'USE' =
      list(
        'USE',
        'USI' =
          list(
            'USI',
            'CHALLC',
            'ELK3C',
            'HERDC',
            'IRONC',
            'POISNC',
            'REDFL',
            'REDFLC',
            'RFL',
            'RLCTRP',
            'SALR4',
            'SLAT2C',
            'SQAW2C',
            'SQUAWP',
            'STANLC',
            'PAHSIW' =
              list('PAHSIW',
                   'PAHH',
                   'PAHP',
                   'PAHTRP'),
            'SALEFT' =
              list('SALEFT',
                   'SALEFW'),
            'YFK' =
              list('YFK',
                   'YANKFK',
                   'CEY',
                   'BASN3C',
                   'STANLE',
                   'YANKWF'),
            'VC2' =
              list('VC2',
                   'VC1',
                   'VALEYC'),
            'STL' =
              list('STL',
                   'SAWT' =
                     list('SAWT',
                          '4JULYC',
                          'ALTULC',
                          'ALTURL',
                          'BEAVEC',
                          'CHAMPC',
                          'DECKEC',
                          'FISHEC',
                          'FRENCC',
                          'GOLDC',
                          'HELLRC',
                          'HUCKLC',
                          'PETTL',
                          'PETTLC',
                          'POLEC',
                          'SAWTRP',
                          'SMILEC',
                          'VATC',
                          'WILLIC',
                          'YELLLC'
                     )
              )
          ))),
  'Salmon_Other' = list(
    '4JUL2C',
    'BARGAC',
    'BIGMAC',
    'BOUL2C',
    'CHAMBC',
    'CHAMWF',
    'CROOC',
    'FLOSSC',
    'FRENCH',
    'HARDC',
    'HAZARC',
    'HORSEC',
    'JERSEC',
    'LSALR',
    'MOOSEC',
    'NFSTRP',
    'PAHSIR',
    'PARTRC',
    'RAPIDR',
    'SABEC',
    'SAJ',
    'SALR1',
    'SALR2',
    'SALR3',
    'SALREF',
    'SALTRP',
    'SHEEPC',
    'SLATEC',
    'TOWERC',
    'WBIRDC',
    'WINDR'
  )
  )



bin_all = list(
  'GRA' =
    list(
      'GRA',
      'Below_GRA' = bin_list[['Below_GRA']],
      'Clearwater' = bin_list[['Clearwater']],
      'Grande_Ronde' = bin_list[['Grande_Ronde']],
      'Imnaha' = bin_list[['Imnaha']],
      'Salmon' = bin_list[['Salmon']],
      'Snake' = bin_list[['Snake']]
    )
)

site_df_init = tibble(SiteID = unlist(bin_all),
                      path = names(unlist(bin_all))) %>%
  mutate(
    path = stringr::str_replace(path,
                                '[[:digit:]]$',
                                ''),
    path = stringr::str_replace(path,
                                'SC$',
                                'SC1'),
    path = ifelse(SiteID == 'LC1',str_replace(path,'LC','LC1'),path),
    path = stringr::str_replace(path,
                                'USI1',
                                'USI'),
    path = stringr::str_replace(path,
                                'LRW1',
                                'LRW'),
    path = stringr::str_replace(path,
                                'JUL[0-9]',
                                'JUL'),
    path = stringr::str_replace(path,
                                'SC2[0-9]$',
                                'SC2'),
    path = stringr::str_replace(path,
                                'SW21',
                                'SW2'),
    path = stringr::str_replace(path,
                                'LRU[0-9]',
                                'LRU'),
    path = stringr::str_replace(path,
                                'Clearwater_Other[0-9]',
                                'Clearwater_Other'),
    path = stringr::str_replace(path,
                                'BSC[0-9]',
                                'BSC'),
    path = stringr::str_replace(path,
                                'IR21',
                                'IR2'),
    path = stringr::str_replace(path,
                                'ZEN[0-9]',
                                'ZEN'),
    path = stringr::str_replace(path,
                                'JOHNSC[0-9]',
                                'JOHNSC'),
    path = stringr::str_replace(path,
                                'TAY[0-9]',
                                'TAY'),
    path = stringr::str_replace(path,
                                'SAWT[0-9]',
                                'SAWT'),
    path = stringr::str_replace(path,
                                'LLR[0-9]',
                                'LLR'),
    path = stringr::str_replace(path,
                                'Salmon_Other[0-9]',
                                'Salmon_Other'),
    path = stringr::str_replace(path,
                                'MFSR_Other[0-9]',
                                'MFSR_Other'),
    path = stringr::str_replace(path,
                                'Snake_Other[0-9]',
                                'Snake_Other'),
    path = stringr::str_replace(path,
                                'Below_GRA_Other[0-9]',
                                'Below_GRA_Other'),
    path = stringr::str_replace(path,
                                'Below_GRA_Other[0-9]',
                                'Below_GRA_Other'),
    path = stringr::str_replace(path,
                                'Below_GRA_Other[0-9]',
                                'Below_GRA_Other'),
    path = ifelse(
      SiteID %in% c('IR1', 'IR4'),
      stringr::str_replace(path,
                           'IR$',
                           SiteID),
      path)) %>%
  mutate(path = ifelse(
    stringr::str_sub(path, start = -nchar(SiteID)) != SiteID,
    paste(path, SiteID, sep = '.'),
    path
  ))

network_descrip = stringr::str_split(site_df_init$path,
                                     '\\.',
                                     simplify = T)
colnames(network_descrip) = paste0('Step', 1:ncol(network_descrip))

site_df = site_df_init %>%
  bind_cols(network_descrip %>%
              as.data.frame()) %>%
  mutate_at(vars(matches('^Step')),
            funs(as.character)) %>%
  mutate(SiteID = factor(SiteID,
                         levels = unique(
                           site_df_init$SiteID
                         ))) %>%
  arrange(SiteID)


return(site_df)
}
